# Project shortcuts.
#
# `make test` runs both suites: the firmware core in native (gcc) and the
# calibration app (pytest). Neither needs the board.

# Many Pro Micro clones ship the Leonardo bootloader and announce themselves
# as such (2341:8036). Check with `arduino-cli board list` and override if
# needed: make build FQBN=arduino:avr:micro
FQBN ?= arduino:avr:leonardo
SKETCH = firmware/handbrake
VERSION_H = firmware/handbrake/version.h
VERSION   := $(shell sed -n 's/^version = "\(.*\)"/\1/p' app/pyproject.toml)
VENV = app/.venv

# The Python environment places the interpreter under Scripts/ on Windows.
VENV_PY = $(if $(wildcard $(VENV)/Scripts/python.exe),$(VENV)/Scripts/python.exe,$(VENV)/bin/python)

.PHONY: help test test-firmware test-app setup-app build flash clean version build-hex

help:
	@echo "make test           run both test suites"
	@echo "make test-firmware  native firmware core tests (gcc)"
	@echo "make test-app       calibration app tests (pytest)"
	@echo "make setup-app      create the Python environment of the app"
	@echo "make detect         identify the board and its FQBN"
	@echo "make build          compile the firmware (arduino-cli required)"
	@echo "make flash PORT=... upload the firmware to the board"
	@echo "make clean          remove the build artifacts"
	@echo "make version          print the project version (pyproject)"
	@echo "make build-hex        build the firmware hex into app data"
	@echo "make package-win      package the Windows exe (run on Windows)"
	@echo "make package-linux    package the Linux AppImage (run on Linux)"

test: test-firmware test-app

test-firmware:
	@$(MAKE) -C tests test

test-app: $(VENV)
	@$(VENV_PY) -m pytest app/tests -q

setup-app: $(VENV)

# --system-site-packages: pywebview's GTK backend needs PyGObject, which pip
# does not provide without a full build toolchain. On Linux the system
# library is already there and lends itself to sharing; on Windows the flag
# has no effect, pywebview going through WebView2 there.
$(VENV):
	@echo "Creating the Python environment..."
	@cd app && uv venv --system-site-packages .venv \
		&& uv pip install --python .venv -e ".[dev,desktop]"

$(VERSION_H): app/pyproject.toml
	@printf '/* Generated by make - do not edit. */\n#define HB_FW_VERSION "%s"\n' "$(VERSION)" > $@

build: $(VERSION_H)
	arduino-cli compile --fqbn $(FQBN) $(SKETCH)

flash:
	@test -n "$(PORT)" || { echo "Specify the port: make flash PORT=/dev/ttyACM0"; exit 1; }
	arduino-cli upload --fqbn $(FQBN) --port $(PORT) $(SKETCH)

# --- Versioning and packaging ---------------------------------------------
# The single source of truth for the version is app/pyproject.toml.
# build-hex writes the generated version files, compiles, and places the
# hex where the app expects it. RELEASE_VERSION= overrides and must equal
# the pyproject version (the CI release tag) - a mismatch is an error.
# arduino-cli names the main output <sketch>.ino.hex (1.5+) or
# <sketch>.ino.<fqbn>.hex (1.0-1.4); the recipe tries both names.
# The recipe shell runs with `set -e`: any failing step (write, compile,
# copy) aborts before the success line, so a failed build can never ship
# a stale hex from a previous run.
APP_DATA = app/loadcraft/data
APP_VERSION_PY = app/loadcraft/_version.py
RELEASE_VERSION ?=

version:
	@echo "$(VERSION)"

build-hex:
	@set -e; if [ -n "$(RELEASE_VERSION)" ] && [ "$(RELEASE_VERSION)" != "$(VERSION)" ]; then \
	    echo "error: RELEASE_VERSION='$(RELEASE_VERSION)' does not match the pyproject version '$(VERSION)'"; \
	    exit 1; fi; \
	v="$(RELEASE_VERSION)"; [ -n "$$v" ] || v="$(VERSION)"; \
	printf '/* Generated by make build-hex - do not edit. */\n#define HB_FW_VERSION "%s"\n' "$$v" > $(VERSION_H); \
	printf '"""Generated by make build-hex - do not edit."""\n__version__ = "%s"\n' "$$v" > $(APP_VERSION_PY); \
	arduino-cli compile --fqbn $(FQBN) --output-dir $(SKETCH)/build $(SKETCH); \
	mkdir -p $(APP_DATA); \
	hex="$(SKETCH)/build/$(notdir $(SKETCH)).ino.hex"; \
	[ -f "$$hex" ] || hex="$(SKETCH)/build/$(notdir $(SKETCH)).ino.$(FQBN).hex"; \
	cp "$$hex" $(APP_DATA)/handbrake.hex; \
	echo "Firmware $$v hex -> $(APP_DATA)/handbrake.hex"

# Detects the board and prints the FQBN to use.
detect:
	arduino-cli board list

clean:
	@$(MAKE) -C tests clean
	rm -rf $(SKETCH)/build
	rm -f $(VERSION_H)
