# Project shortcuts.
#
# `make test` runs both suites: the firmware core in native (gcc) and the
# calibration app (pytest). Neither needs the board.

# Many Pro Micro clones ship the Leonardo bootloader and announce themselves
# as such (2341:8036). Check with `arduino-cli board list` and override if
# needed: make build FQBN=arduino:avr:micro
FQBN ?= arduino:avr:leonardo
SKETCH = firmware/handbrake
VERSION_H = firmware/handbrake/version.h
VERSION   := $(shell sed -n 's/^version = "\(.*\)"/\1/p' app/pyproject.toml)
VENV = app/.venv

# The Python environment places the interpreter under Scripts/ on Windows.
VENV_PY = $(if $(wildcard $(VENV)/Scripts/python.exe),$(VENV)/Scripts/python.exe,$(VENV)/bin/python)

.PHONY: help test test-firmware test-app setup-app build flash clean

help:
	@echo "make test           run both test suites"
	@echo "make test-firmware  native firmware core tests (gcc)"
	@echo "make test-app       calibration app tests (pytest)"
	@echo "make setup-app      create the Python environment of the app"
	@echo "make detect         identify the board and its FQBN"
	@echo "make build          compile the firmware (arduino-cli required)"
	@echo "make flash PORT=... upload the firmware to the board"
	@echo "make clean          remove the build artifacts"

test: test-firmware test-app

test-firmware:
	@$(MAKE) -C tests test

test-app: $(VENV)
	@$(VENV_PY) -m pytest app/tests -q

setup-app: $(VENV)

# --system-site-packages: pywebview's GTK backend needs PyGObject, which pip
# does not provide without a full build toolchain. On Linux the system
# library is already there and lends itself to sharing; on Windows the flag
# has no effect, pywebview going through WebView2 there.
$(VENV):
	@echo "Creating the Python environment..."
	@cd app && uv venv --system-site-packages .venv \
		&& uv pip install --python .venv -e ".[dev,desktop]"

$(VERSION_H): app/pyproject.toml
	@printf '/* Generated by make - do not edit. */\n#define HB_FW_VERSION "%s"\n' "$(VERSION)" > $@

build: $(VERSION_H)
	arduino-cli compile --fqbn $(FQBN) $(SKETCH)

flash:
	@test -n "$(PORT)" || { echo "Specify the port: make flash PORT=/dev/ttyACM0"; exit 1; }
	arduino-cli upload --fqbn $(FQBN) --port $(PORT) $(SKETCH)

# Detects the board and prints the FQBN to use.
detect:
	arduino-cli board list

clean:
	@$(MAKE) -C tests clean
	rm -rf $(SKETCH)/build
	rm -f $(VERSION_H)
